In [1]:
import pandas as pd

In [2]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [3]:
type(nba["Name"])

pandas.core.series.Series

In [4]:
nba.value_counts(ascending=False)

Name             Team                  Position  Height  Weight  College          Salary
Zion Williamson  New Orleans Pelicans  F         6-6     284.0   Duke             34005250.0    1
AJ Green         Milwaukee Bucks       G         6-5     190.0   Northern Iowa    1901769.0     1
AJ Griffin       Atlanta Hawks         F         6-6     220.0   Duke             3712920.0     1
Aaron Gordon     Denver Nuggets        F         6-8     235.0   Arizona          22266182.0    1
Aaron Holiday    Houston Rockets       G         6-0     185.0   UCLA             2346614.0     1
                                                                                               ..
Ayo Dosunmu      Chicago Bulls         G         6-5     200.0   Illinois         6481482.0     1
Azuolas Tubelis  Philadelphia 76ers    F         6-11    245.0   Arizona          559782.0      1
Bam Adebayo      Miami Heat            C-F       6-9     255.0   Kentucky         32600060.0    1
Ben Sheppard     Indiana Pacers        G         6-6     190.0   Belmont          2537172.0     1
Ben Simmons      Brooklyn Nets         G-F       6-10    240.0   Louisiana State  37893408.0    1
Name: count, Length: 475, dtype: int64

In [5]:
nba.head(10)

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
5,Trent Forrest,Atlanta Hawks,G,6-4,210.0,Florida State,508891.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
7,Mouhamed Gueye,Atlanta Hawks,F,6-11,210.0,Washington State,1119563.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
9,Jalen Johnson,Atlanta Hawks,F,6-8,219.0,Duke,2925360.0

In [6]:
nba["Team"].value_counts()

Team
Dallas Mavericks          23
Denver Nuggets            22
Miami Heat                22
Milwaukee Bucks           22
Memphis Grizzlies         22
Indiana Pacers            21
Philadelphia 76ers        21
Washington Wizards        21
Utah Jazz                 21
Oklahoma City Thunder     21
New York Knicks           21
Toronto Raptors           21
Charlotte Hornets         20
Houston Rockets           20
San Antonio Spurs         20
Phoenix Suns              20
Chicago Bulls             19
Minnesota Timberwolves    19
Cleveland Cavaliers       19
Los Angeles Lakers        19
Detroit Pistons           19
Los Angeles Clippers      19
Sacramento Kings          18
Orlando Magic             18
Boston Celtics            18
Atlanta Hawks             18
Golden State Warriors     17
Brooklyn Nets             17
Portland Trail Blazers    17
New Orleans Pelicans      16
Name: count, dtype: int64

In [7]:
nba["Name"].value_counts()

Name
Delon Wright         1
Saddiq Bey           1
Bogdan Bogdanovic    1
Kobe Bufkin          1
Clint Capela         1
                    ..
Dalano Banton        1
Oshae Brissett       1
Malcolm Brogdon      1
Jaylen Brown         1
JD Davison           1
Name: count, Length: 591, dtype: int64

In [8]:
nba["Position"].value_counts

<bound method IndexOpsMixin.value_counts of 0        F
1        G
2        G
3        C
4      F-C
      ...
587      G
588      G
589      F
590      G
591    NaN
Name: Position, Length: 592, dtype: object>

In [9]:
# normalize=True , converts counts into percentage/proportion
nba["Position"].value_counts("normalize = True")

Position
G      0.392123
F      0.320205
C      0.080479
G-F    0.078767
F-C    0.063356
C-F    0.039384
F-G    0.025685
Name: proportion, dtype: float64

In [10]:
nba["Position"].value_counts("normalized = True")*100

Position
G      39.212329
F      32.020548
C       8.047945
G-F     7.876712
F-C     6.335616
C-F     3.938356
F-G     2.568493
Name: proportion, dtype: float64

In [11]:
nba.sample(10)

,Name,Team,Position,Height,Weight,College,Salary
37,Mikal Bridges,Brooklyn Nets,G-F,6-6,209.0,Villanova,21700000.0
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
266,Cam Reddish,Los Angeles Lakers,F-G,6-7,217.0,Duke,2165000.0
14,Dejounte Murray,Atlanta Hawks,G,6-5,180.0,Washington,18214000.0
530,Scottie Barnes,Toronto Raptors,F,6-8,225.0,Florida State,8008680.0
228,Oscar Tshiebwe,Indiana Pacers,F-C,6-9,255.0,Kentucky,559782.0
356,Jose Alvarado,New Orleans Pelicans,G,6-0,179.0,Georgia Tech,NaN
171,Isaiah Stewart,Detroit Pistons,F-C,6-8,250.0,Washington,5266713.0
273,Desmond Bane,Memphis Grizzlies,G,6-5,215.0,TCU,3845083.0
327,Meyers Leonard,Milwaukee Bucks,F-C,7-0,260.0,Illinois,NaN

In [12]:
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# isna() checks whether data is missing or not
nba.isna()

      Name   Team  Position  Height  Weight  College  Salary
0    False  False     False   False   False    False   False
1    False  False     False   False   False    False   False
2    False  False     False   False   False    False   False
3    False  False     False   False   False    False   False
4    False  False     False   False   False    False   False
..     ...    ...       ...     ...     ...      ...     ...
587  False  False     False   False   False    False   False
588  False  False     False   False   False    False   False
589  False  False     False   False   False    False    True
590  False  False     False   False   False    False   False
591   True   True      True    True    True     True    True

[592 rows x 7 columns]

In [14]:
# sum() counts total missing (True) values
nba.isna().sum()

Name          1
Team          1
Position      8
Height        7
Weight        8
College      14
Salary      104
dtype: int64

In [15]:
# isnull() checks missing (NaN) values (same as isna)
nba.isnull()

      Name   Team  Position  Height  Weight  College  Salary
0    False  False     False   False   False    False   False
1    False  False     False   False   False    False   False
2    False  False     False   False   False    False   False
3    False  False     False   False   False    False   False
4    False  False     False   False   False    False   False
..     ...    ...       ...     ...     ...      ...     ...
587  False  False     False   False   False    False   False
588  False  False     False   False   False    False   False
589  False  False     False   False   False    False    True
590  False  False     False   False   False    False   False
591   True   True      True    True    True     True    True

[592 rows x 7 columns]

Dropna function is used to remove the null values

In [16]:
nba.dropna()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [17]:
nba.dropna( how ="any") #Drop the row if ANY value is missing (NaN) in that row

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [18]:
nba.dropna(how="all")

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [19]:
nba.dropna(subset=["College"])

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [20]:
nba.dropna(subset=["College","Salary"])

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [21]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Fillna  method is used to replace the missing NaN values with its arguments
# it is also available on both dataframe and series
nba.fillna(0)

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,0,0,0,0,0.0,0,0.0

In [23]:
nba["Salary"].isnull().sum()

np.int64(104)

In [24]:
nba["Salary"] = nba["Salary"].fillna(0)

In [25]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [26]:
nba["Height"] = nba["Height"].fillna(0)

In [27]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,0,NaN,NaN,0.0

In [28]:
nba.isnull().sum()

Name         1
Team         1
Position     8
Height       0
Weight       8
College     14
Salary       0
dtype: int64

In [29]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    592 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    592 non-null    float64
dtypes: float64(2), object(5)
memory usage: 32.5+ KB

In [30]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [32]:
nba["College"]= nba["College"].fillna(value= "unknown")

In [33]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,0,NaN,unknown,0.0

In [34]:
type(nba)

pandas.core.frame.DataFrame

In [35]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
astype() function

#  The main purpose of astype() is to change the data type of a column or Series.
nba["Salary"] = nba["Salary"].astype(int)

In [43]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122
591,NaN,NaN,NaN,0,NaN,unknown,0

In [38]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary        int64
dtype: object

In [39]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122
591,NaN,NaN,NaN,0,NaN,unknown,0

unique() prints (returns) all unique values in a column without repetition

In [40]:
nba["Team"].unique()

array(['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets',
       'Charlotte Hornets', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Dallas Mavericks', 'Denver Nuggets', 'Detroit Pistons',
       'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies',
       'Miami Heat', 'Milwaukee Bucks', 'Minnesota Timberwolves',
       'New Orleans Pelicans', 'New York Knicks', 'Oklahoma City Thunder',
       'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns',
       'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs',
       'Toronto Raptors', 'Utah Jazz', 'Washington Wizards', nan],
      dtype=object)

nunique() is to count how many unique (different) values are in a column.

In [41]:
nba["Team"].nunique()

30

In [42]:
# unique() does NOT work on a DataFrame
# It only works on a single column (Series).
nba.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [44]:
nba["Position"]= nba["Position"].astype("category")

In [48]:
nba.dtypes

Name          object
Team          object
Position    category
Height        object
Weight       float64
College       object
Salary         int64
dtype: object

In [49]:
nba=pd.read_csv("nba.csv")
nba.head()
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# sort_values()function
# Arrange data in ascending or descending order
# Default is ascending order (A → Z, small → big)
nba.sort_values("Name")

,Name,Team,Position,Height,Weight,College,Salary
122,A.J. Lawson,Dallas Mavericks,G,6-6,179.0,South Carolina,NaN
324,AJ Green,Milwaukee Bucks,G,6-5,190.0,Northern Iowa,1901769.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
141,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,22266182.0
198,Aaron Holiday,Houston Rockets,G,6-0,185.0,UCLA,2346614.0
...,...,...,...,...,...,...,...
83,Zach LaVine,Chicago Bulls,G,6-5,200.0,UCLA,40064220.0
149,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,4306281.0
291,Ziaire Williams,Memphis Grizzlies,F,6-9,185.0,Stanford,4810200.0
370,Zion Williamson,New Orleans Pelicans,F,6-6,284.0,Duke,34005250.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
nba.sort_values(by="Team")

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
17,Trae Young,Atlanta Hawks,G,6-1,164.0,Oklahoma,40064220.0
16,Onyeka Okongwu,Atlanta Hawks,F-C,6-9,240.0,Southern California,8109063.0
15,Miles Norris,Atlanta Hawks,NaN,NaN,NaN,NaN,559782.0
14,Dejounte Murray,Atlanta Hawks,G,6-5,180.0,Washington,18214000.0
...,...,...,...,...,...,...,...
570,Deni Avdija,Washington Wizards,F,6-9,210.0,Maccabi Tel Aviv,6263188.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
579,Anthony Gill,Washington Wizards,F,6-8,230.0,Virginia,1997238.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
nba.sort_values(by="Salary",ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
175,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,51915615.0
461,Kevin Durant,Phoenix Suns,F,6-10,240.0,Texas,47649433.0
261,LeBron James,Los Angeles Lakers,F,6-9,250.0,St. Vincent-St. Mary HS (OH),47607350.0
436,Joel Embiid,Philadelphia 76ers,C-F,7-0,280.0,Kansas,47607350.0
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350.0
...,...,...,...,...,...,...,...
547,Gary Trent Jr.,Toronto Raptors,G-F,6-5,209.0,Duke,NaN
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
584,Kendrick Nunn,Washington Wizards,G,6-3,190.0,Oakland,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
nba[nba["Name"]== "kobe bryant"]

Empty DataFrame
Columns: [Name, Team, Position, Height, Weight, College, Salary]
Index: []

In [55]:
nba = nba.sort_values(["Team","Name"])

In [56]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0

In [ ]:
# It is used to save (export) your DataFrame into a CSV file
nba.to_csv("nba1.csv")

In [60]:
nba.to_excel("nba.xlsx")

In [61]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0

In [62]:
nba.sort_index()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
nba.sort_index(ascending= False)

,Name,Team,Position,Height,Weight,College,Salary
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
...,...,...,...,...,...,...,...
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0

In [64]:
nba

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
...,...,...,...,...,...,...,...
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
580,Tyus Jones,Washington Wizards,G,6-2,196.0,Duke,14000000.0
573,Xavier Cooks,Washington Wizards,F,6-8,183.0,Winthrop,1719864.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# Rank value with the rank method 
nba["Salary"].rank()

6      233.0
1      409.0
4      181.0
3      420.0
8      417.0
       ...
578      NaN
589      NaN
580    385.0
573     94.5
591      NaN
Name: Salary, Length: 592, dtype: float64

In [67]:
nba["Salary"]= nba["Salary"].rank(ascending = False)

In [68]:
nba

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,256.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,80.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,308.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,69.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,72.0
...,...,...,...,...,...,...,...
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
580,Tyus Jones,Washington Wizards,G,6-2,196.0,Duke,104.0
573,Xavier Cooks,Washington Wizards,F,6-8,183.0,Winthrop,394.5
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
nba.sort_values("Salary", ascending = False).head(13)

,Name,Team,Position,Height,Weight,College,Salary
5,Trent Forrest,Atlanta Hawks,G,6-4,210.0,Florida State,488.0
15,Miles Norris,Atlanta Hawks,NaN,NaN,NaN,NaN,458.0
555,Joey Hauser,Utah Jazz,F,6-9,230.0,Michigan State,458.0
540,Markquis Nowell,Toronto Raptors,G,5-8,160.0,Kansas State,458.0
336,Lindell Wigginton,Milwaukee Bucks,G,6-1,189.0,Iowa State,458.0
381,Jaylen Martin,New York Knicks,G,6-6,216.0,NaN,458.0
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,458.0
523,Sir'Jabari Rice,San Antonio Spurs,G,6-4,180.0,Texas,458.0
392,Dylan Windler,New York Knicks,G-F,6-7,196.0,Belmont,458.0
572,Jared Butler,Washington Wizards,G,6-3,193.0,Baylor,458.0
508,Dominick Barlow,San Antonio Spurs,F,6-9,215.0,NaN,458.0
143,Jay Huff,Denver Nuggets,C,7-1,240.0,Virginia,458.0
74,Onuralp Bitim,Chicago Bulls,F,6-6,215.0,NaN,458.0

In [70]:
# new file is read(file name is employee.csv)
import pandas as pd

In [71]:
employee = pd.read_csv("employees.csv")

In [72]:
employee.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [73]:
employee.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [74]:
type(employee)

pandas.core.frame.DataFrame

In [ ]:
employee["Start Date"]= pd.to_datetime(employee["Start Date"], format= "%m/%d/%Y")
# It is used to convert a column into proper DateTime format

In [76]:
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 62.6+ KB

In [77]:
employee.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services

In [78]:
employee["Last Login Time"].head()

0    12:42 PM
1     6:53 AM
2    11:17 AM
3     1:00 PM
4     4:47 PM
Name: Last Login Time, dtype: object

In [79]:
employee["Last Login Time"]= pd.to_datetime(employee["Last Login Time"], format="%I:%M %p").dt.time
# It is used to convert a time column (string format) into proper time format

In [80]:
employee.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services

In [82]:
employee[employee["Gender"]== "Female"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,NaN,Finance
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
990,Robin,Female,1987-07-24,13:35:00,100765,10.982,True,Client Services
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
993,Tina,Female,1997-05-15,15:53:00,56450,19.040,True,Engineering

In [83]:
on_finance_team=employee["Team"]== "Finance"

In [84]:
employee

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [90]:
employee[employee["Senior Management"]==True]
employee[employee["Senior Management"]==True].head()
employee[employee["Salary"]>148500]
employee[employee["Bonus %"]<5]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
19,Donna,Female,2010-07-22,03:48:00,81014,1.894,False,Product
20,Lois,NaN,1995-04-22,19:18:00,64714,4.934,True,Legal
...,...,...,...,...,...,...,...,...
976,Denise,Female,1992-10-19,05:42:00,137954,4.195,True,Legal
985,Stephen,NaN,1983-07-10,20:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,16:58:00,38344,3.794,False,Legal
994,George,Male,2013-06-21,17:47:00,98874,4.479,True,Marketing
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product

In [91]:
employee[employee["First Name"]=="Donald"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
506,Donald,Male,1995-07-14,07:51:00,106472,6.499,True,Client Services
647,Donald,Male,1988-04-06,10:00:00,122920,5.320,False,NaN
909,Donald,Male,1991-08-01,02:25:00,61999,6.466,False,Product

In [92]:
employee.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time              object
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
dtype: object

In [93]:
import pandas as pd

In [94]:
employees= pd.read_csv("employees.csv", parse_dates=["Start Date"],date_format="%M/%d/%Y")
employees["Last Login Time"]= pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Gender"]= employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-01-06 00:08:00,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-01-31 00:03:00,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-01-23 00:04:00,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-01-04 00:03:00,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24 00:01:00,04:47:00,101004,1.389,True,Client Services

In [95]:
employee.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time              object
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
dtype: object

In [96]:
employees= pd.read_csv("employees.csv", parse_dates=["Start Date"],date_format="%M/%d/%Y")
employees["Last Login Time"]= pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"]= employees["Senior Management"].astype(bool)
employees["Gender"]= employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-01-06 00:08:00,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-01-31 00:03:00,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-01-23 00:04:00,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-01-04 00:03:00,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24 00:01:00,04:47:00,101004,1.389,True,Client Services

In [101]:
# filter with more than one condition (AND) At first we define the column and
is_female = employees["Gender"] == "Female"
is_in_finance = employees["Team"] == "Finance"
salary_over_130k = employees["Salary"] > 130000
bonus_above_10 = employees["Bonus %"] > 10

In [102]:
employee.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services

In [104]:
# The duplicated method
# The duplicated method return True if a series value is duplicated
# pandas will mark one occurrence of a repeated values as a non-duplicated
import pandas as pd
employees= pd.read_csv("employees.csv", parse_dates=["Start Date"],date_format="%M/%d/%Y")
employees["Last Login Time"]= pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Gender"]= employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-01-06 00:08:00,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-01-31 00:03:00,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-01-23 00:04:00,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-01-04 00:03:00,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24 00:01:00,04:47:00,101004,1.389,True,Client Services